### PR TITLE
Guzzle 7.0

### PR DESCRIPTION
**Pull request by drjdr**

### CODE REVIEW

**Comment by voicecode-bv** [comment]
Can you please merge this as it allows us to upgrade to Laravel 8? Thanks!

**Comment by jase-languasco** [comment]
any update on this?

**Comment by atanasiuk-hubspot** [comment]
Hi, team. We're going to switch to this soon. Sorry for delay.

**Comment by Orrison** [comment]
bump

**Comment by rossjcooper** [comment]
Bump

**Comment by drjdr** [comment]
#333 solves this

**Pull request merged**
