### PR TITLE
json encode hs_context

### PR DESCRIPTION
**Pull request by morrislaptop**

### CODE REVIEW

**Comment by erikrorstrom** [comment]
Will this not break all implementations for users? Will Hubspot accept the double json_encoded strings as valid?

**Comment by ryanwinchester** [comment]
Can we add an `is_string` check as well?

**Comment by morrislaptop** [comment]
@erikrorstrom @ryanwinchester is_string check added

**Comment by morrislaptop** [comment]
@erikrorstrom @ryanwinchester bump

**Pull request merged**
