### PR TITLE
Create a `HubspotClient` that implements a `HubspotClientInterface`

### PR DESCRIPTION
**Pull request by benjamintoussaint**
Hi,

For the sake of dependency injection and mocking, I needed an `interface` so I've created a `HubspotClient` implementing a `HubspotClientInterface` and made the factory return that `interface` instead of an instance of the factory itself.

What do you think?

Thank you :)

### CODE REVIEW

**Comment by olix21** [comment]
Interfaces could be great to help Mocking things!

**Comment by benjamintoussaint** [comment]
You seem pretty cool with the idea 😬

**Comment by benjamintoussaint** [comment]
🤔

**Comment by benjamintoussaint** [comment]
Hi, would there many any more activity on this PR if I was to adapt the code to pass the checks?

**Comment by atanasiuk-hubspot** [comment]
Hi, @benjamintoussaint! A first thought: this would introduce a breaking change. The API, client is linked to, is legacy, that means the library is not in active development, so any breaking change wouldn't be desirable.

You also might want to switch to a new [HubSpot API](https://developers.hubspot.com/docs/api/overview) and it's corresponding [API client](https://github.com/HubSpot/hubspot-api-php).

**Comment by benjamintoussaint** [comment]
Thanks for your reply @atanasiuk-hubspot!

I will have to take a look at the new API and check whether or not we can easily adapt or code 👍

**Pull request closed without merging**
